/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Datos.Conexion;
import Datos.reservas;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mariangel
 */
public class PnlReservas extends javax.swing.JPanel {

    /**
     * Creates new form reservas
     */
    public PnlReservas() {
        initComponents();
    }
    
    private void limpiar()
    {
        txtId.setText("");
        txtFkVuelo.setText("");
        txtFkPasajero.setText("");
        txtAsiento.setText("");
        txtEstado.setText("");
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblFkVuelo = new javax.swing.JLabel();
        lblFkPasajero = new javax.swing.JLabel();
        lblAsiento = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtFkVuelo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        txtFkPasajero = new javax.swing.JTextField();
        txtAsiento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        Estado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Reservas");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 110, 70));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("Código:");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, 70));

        lblFkVuelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFkVuelo.setForeground(new java.awt.Color(0, 0, 0));
        lblFkVuelo.setText("Vuelo:");
        add(lblFkVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, 40));

        lblFkPasajero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFkPasajero.setForeground(new java.awt.Color(0, 0, 0));
        lblFkPasajero.setText("Pasajero:");
        add(lblFkPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 80, 30));

        lblAsiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAsiento.setForeground(new java.awt.Color(0, 0, 0));
        lblAsiento.setText("Numero Asiento:");
        add(lblAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 150, 40));

        txtId.setBackground(new java.awt.Color(204, 204, 204));
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, 30));

        txtFkVuelo.setBackground(new java.awt.Color(204, 204, 204));
        add(txtFkVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, 30));

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReservas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 370, 370));

        txtFkPasajero.setBackground(new java.awt.Color(204, 204, 204));
        add(txtFkPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, 30));

        txtAsiento.setBackground(new java.awt.Color(204, 204, 204));
        add(txtAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 160, 30));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 60, 30));

        btnNuevo.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 60, 30));

        btnBorrar.setBackground(new java.awt.Color(204, 204, 204));
        btnBorrar.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 60, 30));

        btnConsultar.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 60, 30));

        btnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 70, 30));

        Estado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Estado.setForeground(new java.awt.Color(0, 0, 0));
        Estado.setText("Estado");
        add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        txtEstado.setBackground(new java.awt.Color(204, 204, 204));
        txtEstado.setForeground(new java.awt.Color(0, 0, 0));
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 230, 30));

        lblFondo.setForeground(new java.awt.Color(0, 0, 0));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        lblFondo.setText("jLabel1");
        lblFondo.setMinimumSize(new java.awt.Dimension(891, 493));
        lblFondo.setPreferredSize(new java.awt.Dimension(891, 493));
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        String ID="";
        if ( ID.equals (txtId.getText())){
            JOptionPane.showMessageDialog(null, 
                    "Debe digitar algo en el campo de Identificador",
                    "Mensaje importante", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                if (Conexion.deleteReservas(Integer.parseInt(txtId.getText())) != 0) {
                    JOptionPane.showMessageDialog(null, "Reserva Borrada" );
                }
            } catch (SQLException ex) {
                Logger.getLogger(PnlReservas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        btnConsultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        DefaultListModel miModelo = new DefaultListModel();
        
        ResultSet resultado;
        try {
            resultado = Conexion.listarReservas();
            tblReservas.setModel( DbUtils.resultSetToTableModel(resultado));
        } catch (SQLException ex) {
            Logger.getLogger(PnlReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        reservas miReserva = new reservas();
        miReserva.setId( Integer.parseInt(txtId.getText()  )   );
        miReserva.setNumAsiento( txtAsiento.getText()  );
        miReserva.setEstado(txtEstado.getText());
        miReserva.setFkVuelo (Integer.parseInt(txtFkVuelo.getText()));
        miReserva.setFkPasajero (Integer.parseInt(txtFkPasajero.getText()));

        
        int indice = 0;
        
        try {
            reservas Consultada = Conexion.obtenerReservas( txtId.getText() );
            if (Consultada != null){
                indice = Consultada.getId();
            }
            else {
                indice = 0;
            }
        } catch (SQLException ex) {
            indice = 0;
        }
  
        //---Insertar o Modificar en la tabla
        if (indice == 0){
            try {
                if (Conexion.insertReservas(miReserva) != 0) {
                    JOptionPane.showMessageDialog(null, "Reserva Guardada" );
                }
                        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }else{
           try {
                if (Conexion.updateReservas(miReserva) != 0) {
                    JOptionPane.showMessageDialog(null, "Reserva Modificada" );
                }
                        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }
        btnConsultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String ID="";
        if ( ID.equals (txtId.getText())){
            JOptionPane.showMessageDialog(null, 
                    "Debe digitar algo en el campo de Identificador",
                    "Mensaje importante", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                reservas miReserva = Conexion.obtenerReservas(txtId.getText());
                txtAsiento.setText(miReserva.getNumAsiento());
                txtEstado.setText(miReserva.getEstado());
                txtFkVuelo.setText(String.valueOf(miReserva.getFkVuelo()));
                txtFkPasajero.setText(String.valueOf(miReserva.getFkPasajero()));
            } catch (SQLException ex) {
                Logger.getLogger(PnlReservas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
         int siguiente;
        try {
            siguiente = Conexion.siguienteReserva();
            txtId.setText(String.valueOf(siguiente));
        } catch (SQLException ex) {
            Logger.getLogger(PnlReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estado;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsiento;
    private javax.swing.JLabel lblFkPasajero;
    private javax.swing.JLabel lblFkVuelo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFkPasajero;
    private javax.swing.JTextField txtFkVuelo;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
