/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Datos.Conexion;
import Datos.vuelos;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mariangel
 */
public class PnlVuelos extends javax.swing.JPanel {
    /**
     * Creates new form vuelos
     */
    public PnlVuelos() {
        initComponents();
    }

    private void limpiar()
    {
        txtId.setText("");
        txtNumVuelo.setText("");
        txtOrigen.setText("");
        txtDestino.setText("");
        txtFkAviones.setText("");
        dtpFecha.setDate(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNumVuelo = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNumVuelo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        dtpFecha = new com.toedter.calendar.JDateChooser();
        lblFkAvion = new javax.swing.JLabel();
        txtFkAviones = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Registro de vuelos");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 250, 50));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("Código:");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 40));

        lblNumVuelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumVuelo.setForeground(new java.awt.Color(0, 0, 0));
        lblNumVuelo.setText("Numero Vuelo:");
        add(lblNumVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 40));

        lblOrigen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(0, 0, 0));
        lblOrigen.setText("Origen:");
        add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 30));

        lblDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(0, 0, 0));
        lblDestino.setText("Destino:");
        add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 40));

        txtId.setBackground(new java.awt.Color(204, 204, 204));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, 30));

        txtNumVuelo.setBackground(new java.awt.Color(204, 204, 204));
        add(txtNumVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 30));

        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVuelos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 350, 370));

        txtOrigen.setBackground(new java.awt.Color(204, 204, 204));
        add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, 30));

        txtDestino.setBackground(new java.awt.Color(204, 204, 204));
        add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, 30));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 60, 30));

        btnNuevo.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 60, 30));

        btnBorrar.setBackground(new java.awt.Color(204, 204, 204));
        btnBorrar.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 60, 30));

        btnConsultar.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 60, 30));

        btnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 30));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha:");
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        dtpFecha.setBackground(new java.awt.Color(204, 204, 204));
        add(dtpFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, 30));

        lblFkAvion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFkAvion.setForeground(new java.awt.Color(0, 0, 0));
        lblFkAvion.setText("Avion:");
        add(lblFkAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtFkAviones.setBackground(new java.awt.Color(204, 204, 204));
        txtFkAviones.setForeground(new java.awt.Color(0, 0, 0));
        txtFkAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFkAvionesActionPerformed(evt);
            }
        });
        add(txtFkAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 220, 30));

        lblFondo.setForeground(new java.awt.Color(0, 0, 0));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        lblFondo.setText("jLabel1");
        lblFondo.setMinimumSize(new java.awt.Dimension(796, 501));
        lblFondo.setPreferredSize(new java.awt.Dimension(796, 501));
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        String ID="";
        if ( ID.equals (txtId.getText())){
            JOptionPane.showMessageDialog(null, 
                    "Debe digitar algo en el campo de Identificador",
                    "Mensaje importante", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                if (Conexion.deleteVuelos(Integer.parseInt(txtId.getText())) != 0) {
                    JOptionPane.showMessageDialog(null, "Vuelo Borrado" );
                }
            } catch (SQLException ex) {
                Logger.getLogger(PnlVuelos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        btnConsultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        vuelos miVuelo = new vuelos();
        miVuelo.setId( Integer.parseInt(txtId.getText()  )   );
        miVuelo.setNumVuelo( txtNumVuelo.getText()  );
        miVuelo.setOrigen(txtOrigen.getText());
        miVuelo.setDestino(txtDestino.getText());
        miVuelo.setFecha(dtpFecha.getDate());
        miVuelo.setFkAvion (Integer.parseInt(txtFkAviones.getText()));

        
        int indice = 0;
        
        try {
            vuelos Consultada = Conexion.obtenerVuelos( txtId.getText() );
            if (Consultada != null){
                indice = Consultada.getId();
            }
            else {
                indice = 0;
            }
        } catch (SQLException ex) {
            indice = 0;
        }
  
        //---Insertar o Modificar en la tabla
        if (indice == 0){
            try {
                if (Conexion.insertVuelo(miVuelo) != 0) {
                    JOptionPane.showMessageDialog(null, "Vuelo Guardado" );
                }
                        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }else{
           try {
                if (Conexion.updateVuelos(miVuelo) != 0) {
                    JOptionPane.showMessageDialog(null, "Vuelo Modificado" );
                }
                        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }
        btnConsultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtFkAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFkAvionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFkAvionesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String ID="";
        if ( ID.equals (txtId.getText())){
            JOptionPane.showMessageDialog(null, 
                    "Debe digitar algo en el campo de Identificador",
                    "Mensaje importante", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                vuelos miVuelo = Conexion.obtenerVuelos(txtId.getText());
                txtNumVuelo.setText(miVuelo.getNumVuelo());
                txtOrigen.setText(miVuelo.getOrigen());
                txtDestino.setText(miVuelo.getDestino());
                txtFkAviones.setText(String.valueOf(miVuelo.getFkAvion()));
                dtpFecha.setDate(miVuelo.getFecha());
            } catch (SQLException ex) {
                Logger.getLogger(PnlVuelos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        int siguiente;
        try {
            siguiente = Conexion.siguienteVuelo();
            txtId.setText(String.valueOf(siguiente));
        } catch (SQLException ex) {
            Logger.getLogger(PnlVuelos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
         DefaultListModel miModelo = new DefaultListModel();
        
        ResultSet resultado;
        try {
            resultado = Conexion.listarVuelos();
            tblVuelos.setModel( DbUtils.resultSetToTableModel(resultado));
        } catch (SQLException ex) {
            Logger.getLogger(PnlVuelos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private com.toedter.calendar.JDateChooser dtpFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFkAvion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNumVuelo;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVuelos;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtFkAviones;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumVuelo;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
